# Generated by Django 4.1.5 on 2023-01-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['date'], 'verbose_name': 'Рекламация', 'verbose_name_plural': 'Рекламации'},
        ),
        migrations.AlterModelOptions(
            name='directory',
            options={'ordering': ['name', 'title'], 'verbose_name': 'Справочник', 'verbose_name_plural': 'Справочники'},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['machine_number'], 'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterModelOptions(
            name='technicalservice',
            options={'ordering': ['date'], 'verbose_name': 'ТО', 'verbose_name_plural': 'ТО'},
        ),
    ]
