# Generated by Django 4.1.5 on 2023-01-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_complaint_options_alter_directory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='additional',
            field=models.TextField(blank=True, max_length=256, verbose_name='Комплектация (доп. опции)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='drive_axle_number',
            field=models.CharField(blank=True, max_length=128, unique=True, verbose_name='Зав. № ведущего моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engine_number',
            field=models.CharField(blank=True, max_length=128, unique=True, verbose_name='Зав. № двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_number',
            field=models.CharField(blank=True, max_length=128, unique=True, verbose_name='Зав. № машины'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='steer_axle_number',
            field=models.CharField(blank=True, max_length=128, unique=True, verbose_name='Зав. № управляемого моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmission_number',
            field=models.CharField(blank=True, max_length=128, unique=True, verbose_name='Зав. № трансмиссии'),
        ),
    ]
