# Generated by Django 4.1.5 on 2023-01-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_machine_additional_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['shipping_date'], 'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterField(
            model_name='directory',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
    ]
