# Generated by Django 4.1.5 on 2023-01-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_machine_options_alter_complaint_spares'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-date'], 'verbose_name': 'Рекламация', 'verbose_name_plural': 'Рекламации'},
        ),
        migrations.AlterModelOptions(
            name='technicalservice',
            options={'ordering': ['-date'], 'verbose_name': 'ТО', 'verbose_name_plural': 'ТО'},
        ),
    ]
