# Generated by Django 4.1.5 on 2023-01-29 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_complaint_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalservice',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technisalservice_machine', to='app.machine', verbose_name='Машина'),
        ),
    ]
