# Generated by Django 4.1.5 on 2023-01-29 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_technicalservice_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalservice',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technisalservices', to='app.machine', verbose_name='Машина'),
        ),
    ]
